---
- name:  Pb to test play
  hosts: o1d
  gather_facts: no
  vars:
    - timestamp: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    # - fqdn: "fsp7v12.integ.dev-franceconnect.fr"
    - appname: "fsp3v2-pp"
    - env_filename: "{{ appname | regex_replace('fsp.','fsp') | regex_replace('-.*')}}.j2"
    # - FspId: "{{ fqdn.split('.')[0] }}"
    # - FspEnv: "{{ fqdn.split('.')[1] }}"
    # - AppCore: "{{ fqdn.split('.')[0] | regex_replace('fsp.') }}"
    # - FspOther: "{{ appname | regex_replace('*-')}}"
  tasks:
    # - name: Save file /etc/sudoers before update
    #   copy:
    #     src: /etc/sudoers
    #     dest: /etc/sudoers.{{timestamp}}.bak
    #     remote_src: yes 
    # - name: Display FspId
    #   debug: 
    #     msg: "{{ FspId }}"
    # - name: Display FspEnv
    #   debug: 
    #     msg: "{{ FspEnv }}"
    # - name: Display AppCore
    #   debug: 
    #     msg: "{{ AppCore }}"
    # - name: Display EnvFilename 
    #   debug: 
    #     msg: "{{ env_filename }}"
    - include_role: 
        name: _test
    # - name: Copy template 
    #   template: 
    #     src: "{{ env_filename }}"
    #     dest: /tmp/
